#!/usr/bin/env bash
# Bundle the static web app (repo root) into android/www so Capacitor can package
# it into the APK. The web app is the single source of truth; www/ is generated.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
WWW="$HERE/www"

rm -rf "$WWW"
mkdir -p "$WWW"
cp "$ROOT/index.html" "$WWW/"
cp -r "$ROOT/css" "$ROOT/js" "$ROOT/games" "$ROOT/icons" "$WWW/"

# The packaged app has no backend of its own. It now ships UNCONFIGURED — the
# user sets a sync server in Settings ▸ Sync server (the sync card is grayed out
# until then). A specific default can still be baked in via KEEN_SYNC_BASE.
SYNC_BASE="${KEEN_SYNC_BASE:-}"
cat > "$WWW/js/sync-config.js" <<EOF
// Generated by android/build-www.sh — baked APK sync default (blank = user
// configures it in Settings). Runtime override: localStorage keen.syncBase.
window.KEEN_SYNC_BASE = "$SYNC_BASE";
EOF
echo "APK sync base: ${SYNC_BASE:-(unconfigured — set in Settings)}"

echo "bundled web app into $WWW:"
ls -la "$WWW"
