#!/usr/bin/env bash
# Bundle the static web app (repo root) into android/www so Capacitor can package
# it into the APK. The web app is the single source of truth; www/ is generated.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
WWW="$HERE/www"

rm -rf "$WWW"
mkdir -p "$WWW"
cp "$ROOT/index.html" "$WWW/"
cp -r "$ROOT/css" "$ROOT/js" "$ROOT/games" "$ROOT/icons" "$WWW/"

# The packaged app has no backend of its own, so point server-sync at a real
# server. This overrides the (empty) web js/sync-config.js inside www/ only.
SYNC_BASE="${KEEN_SYNC_BASE:-https://keen456.box.dnsif.ca/}"
cat > "$WWW/js/sync-config.js" <<EOF
// Generated by android/build-www.sh — APK server-sync target.
window.KEEN_SYNC_BASE = "$SYNC_BASE";
EOF
echo "APK sync base: $SYNC_BASE"

echo "bundled web app into $WWW:"
ls -la "$WWW"
